version: "3"

services:
  express-tutorial:
    container_name: "express-tutorial"
    image: express-tutorial
    build:
      context: .
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      APP_ENV: ${APP_ENV}

      PSQL_HOST: ${PSQL_HOST}
      PSQL_PORT: ${PSQL_PORT}
      PSQL_DATABASE: ${PSQL_DATABASE}
      PSQL_USER: ${PSQL_USER}
      PSQL_PASSWORD: ${PSQL_PASSWORD}
      PSQL_SSL: ${PSQL_SSL}
